### ISSUE TITLE
please add more option

### ISSUE THREAD

**Issue by BioBut** [CookieJarApps/BiscuitBrowser#4]
reference/example:

specific website open official app (Google play app, whatsapp app)
https://github.com/mjbdl/Premium-SmartWebView

Night Mode method.. splash screen
https://github.com/dmitrylaas/evobrowser

 lightweight browser app
https://github.com/alandau/sweb

my website not working 
https://www.biobut.com/2020/12/png-image-resizer-multiple-sizes.html

Download manager external support

Bro This Browser Use Android Official Download Manager.
You can change and use this method.
Download request/ start automatically open external app/browser (chrome browser, Firefox browser , other download manager etc.)

**Comment by yitzy299** [comment]
> my website not working
> https://www.biobut.com/2020/12/png-image-resizer-multiple-sizes.html

On chrome desktop, your site is still broken, so it can't be a biscuit browser issue

**Comment by BioBut** [comment]
> > my website not working
> > https://www.biobut.com/2020/12/png-image-resizer-multiple-sizes.html
> 
> On chrome desktop, your site is still broken. Maybe fix it

i fix my website please check

**Comment by yitzy299** [comment]
![image](https://user-images.githubusercontent.com/66269211/115125319-3ca5c980-9fbf-11eb-8792-f0a520744725.png)
Not fixed, and looks like a scam: no google cookies are used

**Comment by CookieJarApps** [comment]
I tested the website in SmartCookieWeb and it now works correctly. In BiscuitBrowser, it doesn't currently work as the browser is missing file upload support, but I'm going to release an update later today that fixes the issue.

**Comment by yitzy299** [comment]
Your site is a scam - make it disappear

**Comment by yitzy299** [comment]
Your site is a scam - make it disappear

**Comment by yitzy299** [comment]
your website is a scam - you do not send google cookies

**Comment by yitzy299** [comment]
Censorship

**Comment by yitzy299** [comment]
🇨🇳
